# 상품코드 별 매출액(판매가 * 판매량) 합계를 출력
# 매출액을 기준으로 내림차순 정렬
# 매출액이 같다면 상품코드를 기준으로 오름차순 정렬
SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) SALES 
FROM PRODUCT P
JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID, O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;