# 보호소에 들어올 당시에는 중성화되지 않음
# 보호소를 나갈 때는 중성화됨
# 아이디, 생물 종, 이름 조회
# 아이디 순으로 조회

SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%' 
AND (B.SEX_UPON_OUTCOME LIKE 'Spayed%' OR B.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID;