# 평균 대여 기간이 7일 이상인 자동차들의 자동차 ID & 평균 대여 기간 리스트 출력
# 평균 대여 기간은 소수점 두 번째 자리에서 반올림
# 결과는 평균 대여 기간을 기준으로 내림차순 정렬, 같다면 자동차ID 기준 내림차순 정렬
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

# SELECT START_DATE, END_DATE, DATEDIFF(END_DATE, START_DATE) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID = 12;