# 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID 순으로 조회

# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_INS
# WHERE ANIMAL_ID NOT IN ( # 들어온 기록 X (ID 존재 X)
#     SELECT ANIMAL_ID FROM ANIMAL_OUTS # 입양간 기록 O (ID 존재 O)
# )
# ORDER BY ANIMAL_ID, NAME;

SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A
RIGHT JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
AND B.ANIMAL_ID IS NOT NULL
ORDER BY ANIMAL_ID, NAME;