# Front End 스킬을 가진 개발자의 정보 조회
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME 
FROM DEVELOPERS D
WHERE EXISTS ( # 프론트엔드 기술 존재하는지 확인
    SELECT 1 FROM SKILLCODES S
    WHERE CATEGORY = 'Front End'
    AND D.SKILL_CODE & S.CODE > 0
)
ORDER BY ID;