SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
    FROM MEMBER_PROFILE
    WHERE MONTH(DATE_OF_BIRTH) = 3 AND # 생일 3월
    GENDER = 'W' AND # 여성 회원
    TLNO IS NOT NULL # 전화번호 NULL인 것 제외
    ORDER BY MEMBER_ID; # 회원 ID 기준 오름차순 정렬