SELECT YEAR(A.DIFFERENTIATION_DATE) YEAR, B.SIZE - A.SIZE_OF_COLONY YEAR_DEV, A.ID
FROM ECOLI_DATA A JOIN (
    # 분화된 연도별 가장 큰 대장균의 크기
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;
