# FISH_INFO 테이블에서 잡은 BASS와 SNAPPER의 수를 출력
# 컬럼명은 FISH_COUNT
SELECT COUNT(FISH_TYPE) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN (
SELECT FISH_TYPE FROM FISH_NAME_INFO
WHERE FISH_NAME IN ('BASS', 'SNAPPER'));
