# 도서 ID(BOOK_ID), 저자명(AUTHOR_NAME), 출판일(PUBLISHED_DATE) 리스트 출력
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE B.CATEGORY = '경제' # '경제' 카테고리에 속하는 도서들
ORDER BY PUBLISHED_DATE; # 출판일 기준 오름차순 정렬